spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:irec}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 30000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.whu.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

yuqiu:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: ${JWT_SECRET_KEY:jwt-test}
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    token-name: token
server:
  port: ${SERVER_PORT:8080}
