export const mockMovies = [
  {
    id: '1',
    title: '无间道',
    type: ['动作', '剧情'],
    year: '2002',
    cover: 'https://picsum.photos/id/1011/300/200',
    description: '一部关于卧底和警匪的经典港片。',
    mainType: 'movie',
    popularity: 98,
  },
  {
    id: '2',
    title: '喜剧之王',
    type: ['喜剧'],
    year: '1999',
    cover: 'https://picsum.photos/id/1012/300/200',
    description: '周星驰的代表作，笑中带泪。',
    mainType: 'movie',
    popularity: 95,
  },
  {
    id: '3',
    title: '霸王别姬',
    type: ['剧情'],
    year: '1993',
    cover: 'https://picsum.photos/id/1013/300/200',
    description: '张国荣主演的文艺巅峰之作。',
    mainType: 'movie',
    popularity: 97,
  },
  {
    id: '4',
    title: '流浪地球',
    type: ['动作', '科幻'],
    year: '2019',
    cover: 'https://picsum.photos/id/1015/300/200',
    description: '中国科幻电影的开山之作。',
    mainType: 'bangumi',
    popularity: 92,
  },
  {
    id: '5',
    title: '哪吒之魔童降世',
    type: ['动画', '奇幻'],
    year: '2019',
    cover: 'https://picsum.photos/id/1025/300/200',
    description: '国产动画电影巅峰，颠覆传统神话。',
    mainType: 'movie',
    popularity: 91,
  },
  {
    id: '6',
    title: '功夫',
    type: ['动作', '喜剧'],
    year: '2004',
    cover: 'https://picsum.photos/id/1035/300/200',
    description: '周星驰风格的武侠喜剧，笑点密集。',
    mainType: 'movie',
    popularity: 93,
  },
  {
    id: '7',
    title: '大话西游之大圣娶亲',
    type: ['奇幻', '爱情'],
    year: '1995',
    cover: 'https://picsum.photos/id/1040/300/200',
    description: '一段充满哲理的爱情故事。',
    mainType: 'movie',
    popularity: 96,
  },
  {
    id: '8',
    title: '三体',
    type: ['科幻', '剧情'],
    year: '2023',
    cover: 'https://picsum.photos/id/1050/300/200',
    description: '改编自刘慈欣小说的宏大科幻剧。',
    mainType: 'bangumi',
    popularity: 90,
  },
  {
    id: '9',
    title: '人生大事',
    type: ['剧情'],
    year: '2022',
    cover: 'https://picsum.photos/id/1060/300/200',
    description: '聚焦殡葬题材，充满人情味的电影。',
    mainType: 'movie',
    popularity: 89,
  },
  {
    id: '10',
    title: '隐入尘烟',
    type: ['剧情'],
    year: '2022',
    cover: 'https://picsum.photos/id/1061/300/200',
    description: '讲述边缘农村人物命运的现实主义佳作。',
    mainType: 'movie',
    popularity: 85,
  },
  {
    id: '11',
    title: '战狼2',
    type: ['动作'],
    year: '2017',
    cover: 'https://picsum.photos/id/1062/300/200',
    description: '中国电影票房历史新高。',
    mainType: 'movie',
    popularity: 94,
  },
  {
    id: '12',
    title: '唐人街探案',
    type: ['喜剧', '悬疑'],
    year: '2015',
    cover: 'https://picsum.photos/id/1063/300/200',
    description: '烧脑又好笑的推理电影。',
    mainType: 'movie',
    popularity: 88,
  },
  {
    id: '13',
    title: '千与千寻',
    type: ['动画', '奇幻'],
    year: '2001',
    cover: 'https://picsum.photos/id/1064/300/200',
    description: '宫崎骏不朽的动画名作。',
    mainType: 'movie',
    popularity: 99,
  },
  {
    id: '14',
    title: '你的名字',
    type: ['动画', '爱情'],
    year: '2016',
    cover: 'https://picsum.photos/id/1065/300/200',
    description: '唯美画风与时空交错的爱情故事。',
    mainType: 'movie',
    popularity: 95,
  },
  {
    id: '15',
    title: '阿凡达',
    type: ['科幻', '冒险'],
    year: '2009',
    cover: 'https://picsum.photos/id/1066/300/200',
    description: '开创3D电影新纪元。',
    mainType: 'movie',
    popularity: 97,
  },
  {
    id: '16',
    title: '盗梦空间',
    type: ['科幻', '惊悚'],
    year: '2010',
    cover: 'https://picsum.photos/id/1067/300/200',
    description: '诺兰代表作，梦境与现实交织。',
    mainType: 'movie',
    popularity: 96,
  },
  {
    id: '17',
    title: '黑客帝国',
    type: ['科幻', '动作'],
    year: '1999',
    cover: 'https://picsum.photos/id/1068/300/200',
    description: '重新定义科幻动作电影。',
    mainType: 'movie',
    popularity: 94,
  },
  {
    id: '18',
    title: '泰坦尼克号',
    type: ['爱情', '剧情'],
    year: '1997',
    cover: 'https://picsum.photos/id/1069/300/200',
    description: '史诗爱情经典。',
    mainType: 'movie',
    popularity: 98,
  },
  {
    id: '19',
    title: '楚门的世界',
    type: ['剧情', '科幻'],
    year: '1998',
    cover: 'https://picsum.photos/id/1070/300/200',
    description: '当人生成为一场直播。',
    mainType: 'movie',
    popularity: 92,
  },
  {
    id: '20',
    title: '放牛班的春天',
    type: ['剧情'],
    year: '2004',
    cover: 'https://picsum.photos/id/1071/300/200',
    description: '音乐改变命运的感人故事。',
    mainType: 'movie',
    popularity: 90,
  },
  {
    id: '21',
    title: '海边的曼彻斯特',
    type: ['剧情'],
    year: '2016',
    cover: 'https://picsum.photos/id/1072/300/200',
    description: '失落与救赎的故事。',
    mainType: 'movie',
    popularity: 88,
  },
  {
    id: '22',
    title: '疯狂动物城',
    type: ['动画', '喜剧'],
    year: '2016',
    cover: 'https://picsum.photos/id/1073/300/200',
    description: '寓教于乐的动物世界。',
    mainType: 'movie',
    popularity: 93,
  },
  {
    id: '23',
    title: '冰雪奇缘',
    type: ['动画', '音乐'],
    year: '2013',
    cover: 'https://picsum.photos/id/1074/300/200',
    description: '席卷全球的迪士尼动画巨作。',
    mainType: 'movie',
    popularity: 91,
  },
  {
    id: '24',
    title: '肖申克的救赎',
    type: ['剧情'],
    year: '1994',
    cover: 'https://picsum.photos/id/1075/300/200',
    description: '信念与自由的传世佳作。',
    mainType: 'movie',
    popularity: 100,
  },
  {
    id: '25',
    title: '这个杀手不太冷',
    type: ['动作', '剧情'],
    year: '1994',
    cover: 'https://picsum.photos/id/1076/300/200',
    description: '温情与杀戮并存的经典。',
    mainType: 'movie',
    popularity: 97,
  },
  {
    id: '26',
    title: '夏洛特烦恼',
    type: ['喜剧', '奇幻'],
    year: '2015',
    cover: 'https://picsum.photos/id/1036/300/200',
    description: '一场意外让人回到过去重新选择人生。',
    mainType: 'movie',
    popularity: 88,
  },
  {
    id: '27',
    title: '摔跤吧！爸爸',
    type: ['剧情', '体育'],
    year: '2016',
    cover: 'https://picsum.photos/id/1037/300/200',
    description: '父女情深与女性励志的结合。',
    mainType: 'movie',
    popularity: 96,
  },
  {
    id: '28',
    title: '寻梦环游记',
    type: ['动画', '冒险'],
    year: '2017',
    cover: 'https://picsum.photos/id/1038/300/200',
    description: '音乐与亲情交织的感人故事。',
    mainType: 'bangumi',
    popularity: 93,
  },
  {
    id: '29',
    title: '速度与激情7',
    type: ['动作', '犯罪'],
    year: '2015',
    cover: 'https://picsum.photos/id/1039/300/200',
    description: '家人永远是最重要的。',
    mainType: 'movie',
    popularity: 89,
  },
  {
    id: '30',
    title: '绿皮书',
    type: ['剧情', '传记'],
    year: '2018',
    cover: 'https://picsum.photos/id/1040/300/200',
    description: '跨越种族的深厚友情。',
    mainType: 'movie',
    popularity: 94,
  },
  {
    id: '31',
    title: '头号玩家',
    type: ['科幻', '动作'],
    year: '2018',
    cover: 'https://picsum.photos/id/1041/300/200',
    description: '虚拟现实世界的大冒险。',
    mainType: 'movie',
    popularity: 91,
  },
  {
    id: '32',
    title: '阿凡达',
    type: ['科幻', '冒险'],
    year: '2009',
    cover: 'https://picsum.photos/id/1042/300/200',
    description: '视觉特效的革命之作。',
    mainType: 'movie',
    popularity: 98,
  },
  {
    id: '33',
    title: '泰坦尼克号',
    type: ['爱情', '剧情'],
    year: '1997',
    cover: 'https://picsum.photos/id/1043/300/200',
    description: '永恒的爱情经典。',
    mainType: 'movie',
    popularity: 99,
  },
  {
    id: '34',
    title: '阿甘正传',
    type: ['剧情', '传记'],
    year: '1994',
    cover: 'https://picsum.photos/id/1044/300/200',
    description: '笨蛋也能改变世界。',
    mainType: 'movie',
    popularity: 97,
  },
  {
    id: '35',
    title: '狮子王',
    type: ['动画', '冒险'],
    year: '1994',
    cover: 'https://picsum.photos/id/1045/300/200',
    description: '迪士尼不朽的成长寓言。',
    mainType: 'bangumi',
    popularity: 95,
  },
  {
    id: '36',
    title: '驯龙高手',
    type: ['动画', '奇幻'],
    year: '2010',
    cover: 'https://picsum.photos/id/1046/300/200',
    description: '人与龙之间的温情故事。',
    mainType: 'bangumi',
    popularity: 91,
  },
  {
    id: '37',
    title: '冰雪奇缘',
    type: ['动画', '音乐'],
    year: '2013',
    cover: 'https://picsum.photos/id/1047/300/200',
    description: 'Let it go~ 的奇幻冒险。',
    mainType: 'bangumi',
    popularity: 93,
  },
  {
    id: '38',
    title: '神偷奶爸',
    type: ['动画', '喜剧'],
    year: '2010',
    cover: 'https://picsum.photos/id/1048/300/200',
    description: '坏蛋变奶爸，暖心又搞笑。',
    mainType: 'bangumi',
    popularity: 90,
  },
  {
    id: '39',
    title: '爱乐之城',
    type: ['爱情', '音乐'],
    year: '2016',
    cover: 'https://picsum.photos/id/1049/300/200',
    description: '一段遗憾而美丽的爱情梦。',
    mainType: 'movie',
    popularity: 94,
  },
  {
    id: '40',
    title: '速度与激情9',
    type: ['动作', '惊悚'],
    year: '2021',
    cover: 'https://picsum.photos/id/1050/300/200',
    description: '家族仍在继续狂飙。',
    mainType: 'movie',
    popularity: 85,
  },
  {
    id: '41',
    title: '钢铁侠',
    type: ['动作', '科幻'],
    year: '2008',
    cover: 'https://picsum.photos/id/1051/300/200',
    description: '漫威宇宙的起点。',
    mainType: 'movie',
    popularity: 97,
  },
  {
    id: '42',
    title: '复仇者联盟4',
    type: ['动作', '科幻'],
    year: '2019',
    cover: 'https://picsum.photos/id/1052/300/200',
    description: '终局之战，致敬十年。',
    mainType: 'movie',
    popularity: 99,
  },
  {
    id: '43',
    title: '海边的曼彻斯特',
    type: ['剧情'],
    year: '2016',
    cover: 'https://picsum.photos/id/1053/300/200',
    description: '抚平内心伤痛的旅程。',
    mainType: 'movie',
    popularity: 85,
  },
  {
    id: '44',
    title: '调音师',
    type: ['惊悚', '喜剧'],
    year: '2018',
    cover: 'https://picsum.photos/id/1054/300/200',
    description: '局中局中的局。',
    mainType: 'movie',
    popularity: 93,
  },
  {
    id: '45',
    title: '海王',
    type: ['动作', '奇幻'],
    year: '2018',
    cover: 'https://picsum.photos/id/1055/300/200',
    description: '海底王国的传奇英雄。',
    mainType: 'movie',
    popularity: 90,
  },
  {
    id: '46',
    title: '蜘蛛侠：平行宇宙',
    type: ['动画', '科幻'],
    year: '2018',
    cover: 'https://picsum.photos/id/1056/300/200',
    description: '多元宇宙的视觉革命。',
    mainType: 'bangumi',
    popularity: 94,
  },
  {
    id: '47',
    title: '瞬息全宇宙',
    type: ['科幻', '动作'],
    year: '2022',
    cover: 'https://picsum.photos/id/1057/300/200',
    description: '疯狂跨宇宙之旅。',
    mainType: 'movie',
    popularity: 92,
  },
  {
    id: '48',
    title: '信条',
    type: ['科幻', '惊悚'],
    year: '2020',
    cover: 'https://picsum.photos/id/1058/300/200',
    description: '时间的正逆熵操作。',
    mainType: 'movie',
    popularity: 93,
  },
  {
    id: '49',
    title: '寄生虫',
    type: ['惊悚', '剧情'],
    year: '2019',
    cover: 'https://picsum.photos/id/1059/300/200',
    description: '贫富之间的生存较量。',
    mainType: 'movie',
    popularity: 98,
  },
  {
    id: '50',
    title: '小丑',
    type: ['剧情', '犯罪'],
    year: '2019',
    cover: 'https://picsum.photos/id/1060/300/200',
    description: '边缘人的悲剧史诗。',
    mainType: 'movie',
    popularity: 97,
  }
]

export const mockComments = {
  '1': [
    { id: 'c1', user: '用户A', text: '太经典了！' },
    { id: 'c2', user: '用户B', text: '港片巅峰。' },
  ],
  '2': [{ id: 'c3', user: '喜剧粉', text: '看十遍都不腻。' }],
  '5': [{ id: 'c5', user: '动画爱好者', text: '哪吒帅爆了。' }],
  '13': [{ id: 'c13', user: '宫崎骏迷', text: '永远的童年回忆。' }],
  '16': [{ id: 'c16', user: '梦境控', text: '需要多刷几次才能懂。' }],
  '24': [{ id: 'c24', user: '自由人', text: '励志神作，没有之一。' }],
  '50': [{ id: 'c50', user: '影评人', text: '这部还不错。' }],
}
